In [1]:
import pandas as pd
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
from glob import glob
import os
from PIL import Image
import cv2
from tqdm import tqdm

In [2]:
df = pd.read_csv('PATH_TO_DATA/train_256_bbs_final.csv')
df

,challenge_id,class,referable,gradable,x1,y1,x2,y2
0,TRAIN000011,NRG,0,0,121.000000,84.000000,192.000000,167.0
1,TRAIN000013,NRG,0,0,64.000000,103.000000,114.000000,170.0
2,TRAIN000023,NRG,0,0,36.000000,67.000000,101.000000,135.0
3,TRAIN000030,NRG,0,0,122.000000,85.000000,199.000000,157.0
4,TRAIN000031,NRG,0,0,-1.000000,-1.000000,-1.000000,-1.0
...,...,...,...,...,...,...,...,...
20283,TRAIN101402,NRG,0,0,-1.000000,-1.000000,-1.000000,-1.0
20284,TRAIN101406,NRG,0,0,-1.000000,-1.000000,-1.000000,-1.0
20285,TRAIN101410,NRG,0,0,182.000000,84.000000,249.000000,155.0
20286,TRAIN101417,NRG,0,0,73.800003,179.800003,192.199997,255.0
20287,TRAIN101428,NRG,0,0,-1.000000,-1.000000,-1.000000,-1.0

In [3]:
# Select images without bounding box only

df_noBox = df[df['x1'] == -1]
df_noBox

      challenge_id class  referable  gradable   x1   y1   x2   y2
4      TRAIN000031   NRG          0         0 -1.0 -1.0 -1.0 -1.0
8      TRAIN000060    RG          1         0 -1.0 -1.0 -1.0 -1.0
17     TRAIN000103   NRG          0         0 -1.0 -1.0 -1.0 -1.0
19     TRAIN000106    RG          1         0 -1.0 -1.0 -1.0 -1.0
20     TRAIN000119   NRG          0         0 -1.0 -1.0 -1.0 -1.0
...            ...   ...        ...       ...  ...  ...  ...  ...
20268  TRAIN101342   NRG          0         0 -1.0 -1.0 -1.0 -1.0
20276  TRAIN101366   NRG          0         0 -1.0 -1.0 -1.0 -1.0
20283  TRAIN101402   NRG          0         0 -1.0 -1.0 -1.0 -1.0
20284  TRAIN101406   NRG          0         0 -1.0 -1.0 -1.0 -1.0
20287  TRAIN101428   NRG          0         0 -1.0 -1.0 -1.0 -1.0

[3933 rows x 8 columns]

In [4]:
for img in tqdm(df_noBox['challenge_id']):
    
    path = glob(os.path.join('PATH_TO_DATA','AIROGS_train','*',img+'*'))[-1]    
    new_path ='PATH_TO_SAVE_CROPPED_IMAGES'

    os.makedirs(new_path.replace(os.path.basename(new_path),''),exist_ok=True)
    
    im = plt.imread(path) 
    w,h,_ = im.shape
    
    transform = transforms.Compose([
      transforms.ToTensor(),                            
      transforms.CenterCrop(w*0.85),
      transforms.Resize((512, 512))
    ])

    _img = transform(im)
    _img = (_img.moveaxis(0, -1).numpy() * 255).astype('uint8')
    
    assert cv2.imwrite(f'PATH_TO_SAVE_CROPPED_IMAGES/{img}.jpg', cv2.cvtColor(_img, cv2.COLOR_RGB2BGR))

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 3933/3933 [19:43<00:00,  3.32it/s]